backend:
  name: git-gateway
  repo: brucethai97/cms-test-app
  branch: main
  identity_url: https://auth.decapbridge.com/sites/543b5bb6-ad87-45d8-b715-fadd47c31ffb
  gateway_url: https://gateway.decapbridge.com

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'blogs'
    label: 'Blogs'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'string' }
      - { label: 'Read Time', name: 'readTime', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
        field: { label: 'Tag', name: 'tag', widget: 'string' }
      - { label: 'Featured', name: 'featured', widget: 'string' }
      - { label: 'Published', name: 'published', widget: 'string' }
      - label: 'SEO'
        name: 'seo'
        widget: 'object'
        fields:
          - { label: 'SEO Title', name: 'title', widget: 'string' }
          - { label: 'SEO Description', name: 'description', widget: 'text' }
          - label: 'Keywords'
            name: 'keywords'
            widget: 'list'
            field: { label: 'Keyword', name: 'keyword', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'home'
    label: 'Home'
    folder: 'content/home'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Sections'
        name: 'sections'
        widget: 'list'
        fields:
          - { label: 'Section Title', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'content', widget: 'text' }
