backend:
  name: git-gateway
  repo: brucethai97/cms-test-app
  branch: main
  identity_url: https://auth.decapbridge.com/sites/543b5bb6-ad87-45d8-b715-fadd47c31ffb
  gateway_url: https://gateway.decapbridge.com

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'blogs'
    label: 'Blogs'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'frontmatter'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Sections'
        name: 'sections'
        widget: 'list'
        fields:
          - { label: 'Section Title', name: 'title', widget: 'string' }
          - { label: 'Content', name: 'content', widget: 'text' }
  - name: 'home'
    label: 'Home'
    folder: 'content/home'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'frontmatter'
    fields:
      - { label: 'Header', name: 'header', widget: 'string' }
